fix(prometheus.scrape): Update arguments and targets even if `scrape_native_histograms` and `extra_metrics` are updated [backport] (#5792)
## Backport of #5787

This PR backports #5787 to release/v1.14.

### Original PR Author
@ptodev

### Description
### Pull Request Details

Changes to `scrape_native_histograms` and `extra_metrics` can only take
effect after a restart of the component. In a future PR we could get the
scrape pool to restart so that changes to those components can take
effect even if the config is reloaded.

The main issue with the current code is that targets won't be updated.
So even though the component attempts to run the old ("good") config,
that old config contains stale targets. Therefore the scraper isn't
picking up any new targets. It may also try to scrape old targets which
no longer exist.

This PR also fixes a problem where an invalid config in general can
cause stale targets. It's because Update() returns before targets can be
updated.

<details>

<summary>The tests fail when I comment out the change in
scrape.go</summary>

```
└─▪ go test .
ts=2026-03-13T20:25:39.826105Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:39.826579Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:39.829549Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:39.829657Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:39.83196Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:39.832063Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:39.833304Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:39.833419Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:39.838636Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:39.838759Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:44.92322Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:44.92322Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:44.92337Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:44.923383Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:44.930673Z level=info msg="scrape manager stopped"
ts=2026-03-13T20:25:44.934526Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:44.934687Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:44.936428Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:44.936503Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:44.942781Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:44.94289Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:25:44.944278Z level=info msg="scrape manager stopped"
ts=2026-03-13T20:25:49.848985Z level=info msg="scrape manager stopped"
ts=2026-03-13T20:25:49.947027Z level=info msg="scrape manager stopped"
ts=2026-03-13T20:25:50.011818Z level=info msg="scrape manager stopped"
ts=2026-03-13T20:25:50.016656Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:50.016691Z level=debug msg="passed new targets to scrape manager"
level=debug test=TestCustomDialer ts=20:25:55.071 msg="accepted new in-memory connection"
level=debug test=TestCustomDialer ts=20:25:55.071 msg="dialed to in-memory listener"
ts=2026-03-13T20:25:55.073626Z level=info msg="scrape manager stopped"
ts=2026-03-13T20:25:55.204507Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:25:55.205275Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:26:00.306499Z level=info msg="scrape manager stopped"
ts=2026-03-13T20:26:00.422209Z level=debug msg="scrape config was updated"
ts=2026-03-13T20:26:00.422455Z level=debug msg="passed new targets to scrape manager"
ts=2026-03-13T20:26:05.523946Z level=info msg="scrape manager stopped"
ts=2026-03-13T20:26:05.528546Z level=debug msg="scrape config was updated" component_path=prometheus.scrape component_id=targets_are_updated
ts=2026-03-13T20:26:05.528653Z level=debug msg="passed new targets to scrape manager" component_path=prometheus.scrape component_id=targets_are_updated
ts=2026-03-13T20:26:10.601378Z level=debug msg="scrape config was updated" component_path=prometheus.scrape component_id=targets_are_updated
ts=2026-03-13T20:26:10.601752Z level=debug msg="passed new targets to scrape manager" component_path=prometheus.scrape component_id=targets_are_updated
ts=2026-03-13T20:26:15.552585Z level=info msg="scrape manager stopped" component_path=prometheus.scrape component_id=targets_are_updated
ts=2026-03-13T20:26:15.57111Z level=debug msg="scrape config was updated" component_path=prometheus.scrape component_id=scrape_native_histograms_change_is_ignored_but_component_continues_with_updated_targets
ts=2026-03-13T20:26:15.571333Z level=debug msg="passed new targets to scrape manager" component_path=prometheus.scrape component_id=scrape_native_histograms_change_is_ignored_but_component_continues_with_updated_targets
ts=2026-03-13T20:26:20.623134Z level=info msg="scrape manager stopped" component_path=prometheus.scrape component_id=scrape_native_histograms_change_is_ignored_but_component_continues_with_updated_targets
ts=2026-03-13T20:26:20.629026Z level=debug msg="scrape config was updated" component_path=prometheus.scrape component_id=extra_metrics_change_is_ignored_but_component_continues_with_updated_targets
ts=2026-03-13T20:26:20.629441Z level=debug msg="passed new targets to scrape manager" component_path=prometheus.scrape component_id=extra_metrics_change_is_ignored_but_component_continues_with_updated_targets
ts=2026-03-13T20:26:25.680582Z level=info msg="scrape manager stopped" component_path=prometheus.scrape component_id=extra_metrics_change_is_ignored_but_component_continues_with_updated_targets
ts=2026-03-13T20:26:25.705794Z level=debug msg="scrape config was updated" component_path=prometheus.scrape component_id=targets_are_updated_even_when_ApplyConfig_fails
ts=2026-03-13T20:26:25.706469Z level=debug msg="passed new targets to scrape manager" component_path=prometheus.scrape component_id=targets_are_updated_even_when_ApplyConfig_fails
ts=2026-03-13T20:26:30.827503Z level=error msg="error reloading scrape pool" component_path=prometheus.scrape component_id=targets_are_updated_even_when_ApplyConfig_fails err="error creating HTTP client: unable to read CA cert: unable to read file /nonexistent/ca.pem: open /nonexistent/ca.pem: no such file or directory" scrape_pool=test_job
ts=2026-03-13T20:26:40.829039Z level=info msg="scrape manager stopped" component_path=prometheus.scrape component_id=targets_are_updated_even_when_ApplyConfig_fails
--- FAIL: TestRuntimeUpdate (35.31s)
    --- FAIL: TestRuntimeUpdate/scrape_native_histograms_change_is_ignored_but_component_continues_with_updated_targets (5.07s)
        scrape_test.go:1175: 
                Error Trace:    /Users/paulintodev/Documents/GitHub/alloy-1/internal/component/prometheus/scrape/scrape_test.go:1175
                Error:          Received unexpected error:
                                scrape_native_histograms cannot be updated at runtime
                Test:           TestRuntimeUpdate/scrape_native_histograms_change_is_ignored_but_component_continues_with_updated_targets
    --- FAIL: TestRuntimeUpdate/extra_metrics_change_is_ignored_but_component_continues_with_updated_targets (5.06s)
        scrape_test.go:1175: 
                Error Trace:    /Users/paulintodev/Documents/GitHub/alloy-1/internal/component/prometheus/scrape/scrape_test.go:1175
                Error:          Received unexpected error:
                                extra_metrics cannot be updated at runtime
                Test:           TestRuntimeUpdate/extra_metrics_change_is_ignored_but_component_continues_with_updated_targets
    --- FAIL: TestRuntimeUpdate/targets_are_updated_even_when_ApplyConfig_fails (15.15s)
        scrape_test.go:1178: 
                Error Trace:    /Users/paulintodev/Documents/GitHub/alloy-1/internal/component/prometheus/scrape/scrape_test.go:1146
                                                        /Users/paulintodev/Documents/GitHub/alloy-1/internal/component/prometheus/scrape/scrape_test.go:1179
                                                        /Users/paulintodev/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.darwin-arm64/src/runtime/asm_arm64.s:1268
                Error:          Should be true
                Messages:       server_b_up should appear even when ApplyConfig fails
        scrape_test.go:1178: 
                Error Trace:    /Users/paulintodev/Documents/GitHub/alloy-1/internal/component/prometheus/scrape/scrape_test.go:1178
                Error:          Condition never satisfied
                Test:           TestRuntimeUpdate/targets_are_updated_even_when_ApplyConfig_fails
                Messages:       post-update check timed out
FAIL
FAIL    github.com/grafana/alloy/internal/component/prometheus/scrape   61.987s
FAIL
```

</details>

### PR Checklist

<!-- Remove items that do not apply. For completed items, change [ ] to
[x]. -->

- [ ] Documentation added
- [x] Tests updated
- [ ] Config converters updated


---
*This backport was created automatically.*

Co-authored-by: Paulin Todev <paulin.todev@gmail.com>