chore: Update to runners to MacOS 15 (#5835)
There have been [build
failures](https://github.com/grafana/alloy/actions/runs/23295451532/job/67741614844?pr=5539)
recently. Updating the runner seems to fix them.


```
# github.com/99designs/go-keychain
Error: ../../../../go/pkg/mod/github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4/macos.go:70:13: could not determine what C.SecAccessCreate refers to
Error: ../../../../go/pkg/mod/github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4/macos.go:155:13: could not determine what C.SecKeychainCreate refers to
Error: ../../../../go/pkg/mod/github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4/macos.go:191:20: could not determine what C.SecKeychainGetStatus refers to
Error: ../../../../go/pkg/mod/github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4/macos.go:121:13: could not determine what C.SecKeychainItemDelete refers to
Error: ../../../../go/pkg/mod/github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4/macos.go:226:20: could not determine what C.SecKeychainLock refers to
Error: ../../../../go/pkg/mod/github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4/macos.go:200:23: could not determine what C.SecKeychainOpen refers to
Error: ../../../../go/pkg/mod/github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4/macos.go:216:20: could not determine what C.SecKeychainUnlock refers to
Error: ../../../../go/pkg/mod/github.com/99designs/go-keychain@v0.0.0-20191008050251-8e49817e8af4/macos.go:89:13: could not determine what C.SecTrustedApplicationCreateFromPath refers to
```

---------

Co-authored-by: Karl Persson <23356117+kalleep@users.noreply.github.com>